/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/porsche-desktop.glb -t -k -K -r public -o src/components/Porsche.tsx 
Author: n.brizitskaya (https://sketchfab.com/n.brizitskaya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-with-interior-877b1bc1739f4a2bb65d62fd7ffd9f75
Title: Porsche 911 with interior
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    reisin_all_reisin_0: THREE.Mesh
    plastic_exterior_bl_pl_M_ext_0: THREE.Mesh
    windows_main_windows_0: THREE.Mesh
    windows_main_windows_edge_0: THREE.Mesh
    black_metal_all_black_metal_0: THREE.Mesh
    mirror_middle_Mirror_0: THREE.Mesh
    carbon_all_carbon_int_0: THREE.Mesh
    body_all_body_main_0: THREE.Mesh
    lights_pattern_all_headlights_pattern_0: THREE.Mesh
    window_black_transparent_windows_dots_0: THREE.Mesh
    body_circles_body_main_0: THREE.Mesh
    body_circles_invisible_all_0: THREE.Mesh
    number_plate_number_plate1_0: THREE.Mesh
    monitors_seconds_monitor_0: THREE.Mesh
    reflectors_all_reflectors_0: THREE.Mesh
    red_light_back_red_light_main_0: THREE.Mesh
    service_black_invisible_all_0: THREE.Mesh
    glossy_plastic_bl_pl__GL_int_ext_0: THREE.Mesh
    chrome_int_chrom_int_0: THREE.Mesh
    headlights_flash_lights_0: THREE.Mesh
    pipes_pipes_chrom_0: THREE.Mesh
    steering_wheel_signs_pl_leather_int_0: THREE.Mesh
    plast_leather_all_pl_leather_int_0: THREE.Mesh
    dynamics_all_dynamics_0: THREE.Mesh
    trans_covers_lights_0: THREE.Mesh
    upholstery_all_upholstery_0: THREE.Mesh
    logo_all_LOGO1_0: THREE.Mesh
    belts_all_belts_0: THREE.Mesh
    headlights_plastics_hedlights_grid_0: THREE.Mesh
    headlights_plastics_headlights_plastic_ring_0: THREE.Mesh
    rugs_all_rug_interior_0: THREE.Mesh
    leather_all_leather_int_0: THREE.Mesh
    leather_all_leather_seam_0: THREE.Mesh
    leather_all_leather_perforated_0: THREE.Mesh
    plastic_all_bl_pl_M_int_0: THREE.Mesh
    plastic_all_bl_pl_M_int_0_1: THREE.Mesh
    plastic_all_interior_grid_0: THREE.Mesh
    mirror_door_1_Mirror_0: THREE.Mesh
    reisin__door_1_reisin_0: THREE.Mesh
    plastic_exterior_door_1_bl_pl_M_ext_0: THREE.Mesh
    carbon__door_1_carbon_int_0: THREE.Mesh
    dynamics_door_1_dynamics_0: THREE.Mesh
    screw_door_1_black_metal_0: THREE.Mesh
    logo_door_1_LOGO1_0: THREE.Mesh
    reflector_door_1_reflectors_0: THREE.Mesh
    leather_door_1_leather_int_0: THREE.Mesh
    leather_door_1_leather_seam_0: THREE.Mesh
    body__door_1_body_main_0: THREE.Mesh
    window_door_1_windows_0: THREE.Mesh
    window_door_1_windows_edge_0: THREE.Mesh
    plastic_door_1_bl_pl_M_int_0: THREE.Mesh
    mirror_cover_door_1_monitor_0: THREE.Mesh
    chrome_door_1_chrom_int_0: THREE.Mesh
    leathplast_door_1_pl_leather_int_0: THREE.Mesh
    mirror_door_2_Mirror_0: THREE.Mesh
    body_door_2_body_main_0: THREE.Mesh
    plastic_door_2_bl_pl_M_int_0: THREE.Mesh
    leath_plast_door_2_pl_leather_int_0: THREE.Mesh
    chrome__door_2_chrom_int_0: THREE.Mesh
    dynamic_door_2_dynamics_0: THREE.Mesh
    body_all_Ext_3_body_main_0: THREE.Mesh
    reflectors__door_2_reflectors_0: THREE.Mesh
    carbon__door_2_carbon_int_0: THREE.Mesh
    logo_door_2_LOGO1_0: THREE.Mesh
    screw_door_2_black_metal_0: THREE.Mesh
    leather_door_2_leather_int_0: THREE.Mesh
    leather_door_2_leather_seam_0: THREE.Mesh
    plastic_exterior__door_2_bl_pl_M_ext_0: THREE.Mesh
    reisin__door_2_reisin_0: THREE.Mesh
    window_door_2_windows_0: THREE.Mesh
    window_door_2_windows_edge_0: THREE.Mesh
    mirror_cover_door_2_monitor_0: THREE.Mesh
    wheel_FL_wheel_rim_rim_black_0: THREE.Mesh
    wheel_FL_wheel_rim_rim_chrome_0: THREE.Mesh
    wheel_FL_AO_tire_main_tires_0: THREE.Mesh
    wheel_FL_discs_Discs_0: THREE.Mesh
    wheel_FR_wheel_rim_rim_black_0: THREE.Mesh
    wheel_FR_wheel_rim_rim_chrome_0: THREE.Mesh
    wheel_FR_AO_tire_main_tires_0: THREE.Mesh
    wheel_FR_discs_Discs_0: THREE.Mesh
    wheel_RL_wheel_rim_rim_black_0: THREE.Mesh
    wheel_RL_wheel_rim_rim_chrome_0: THREE.Mesh
    wheel_RL_AO_tire_main_tires_0: THREE.Mesh
    wheel_RL_discs_Discs_0: THREE.Mesh
    wheel_RR_wheel_rim_rim_black_0: THREE.Mesh
    wheel_RR_wheel_rim_rim_chrome_0: THREE.Mesh
    wheel_RR_AO_tire_main_tires_0: THREE.Mesh
    wheel_RR_discs_Discs_0: THREE.Mesh
    brake_FL: THREE.Mesh
    brake_FR: THREE.Mesh
    brake_RL: THREE.Mesh
    brake_RR: THREE.Mesh
    hardware_FL: THREE.Mesh
    hardware_FR: THREE.Mesh
    hardware_RL: THREE.Mesh
    hardware_RR: THREE.Mesh
  }
  materials: {
    reisin: THREE.MeshStandardMaterial
    bl_pl_M_ext: THREE.MeshStandardMaterial
    windows: THREE.MeshStandardMaterial
    windows_edge: THREE.MeshStandardMaterial
    black_metal: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    carbon_int: THREE.MeshPhysicalMaterial
    body_main: THREE.MeshPhysicalMaterial
    headlights_pattern: THREE.MeshStandardMaterial
    windows_dots: THREE.MeshStandardMaterial
    invisible_all: THREE.MeshStandardMaterial
    number_plate1: THREE.MeshStandardMaterial
    monitor: THREE.MeshStandardMaterial
    reflectors: THREE.MeshStandardMaterial
    red_light_main: THREE.MeshStandardMaterial
    bl_pl__GL_int_ext: THREE.MeshStandardMaterial
    chrom_int: THREE.MeshStandardMaterial
    lights: THREE.MeshPhysicalMaterial
    pipes_chrom: THREE.MeshStandardMaterial
    pl_leather_int: THREE.MeshStandardMaterial
    dynamics: THREE.MeshStandardMaterial
    upholstery: THREE.MeshStandardMaterial
    LOGO1: THREE.MeshPhysicalMaterial
    belts: THREE.MeshStandardMaterial
    hedlights_grid: THREE.MeshStandardMaterial
    headlights_plastic_ring: THREE.MeshStandardMaterial
    rug_interior: THREE.MeshStandardMaterial
    leather_int: THREE.MeshStandardMaterial
    leather_seam: THREE.MeshStandardMaterial
    leather_perforated: THREE.MeshStandardMaterial
    bl_pl_M_int: THREE.MeshStandardMaterial
    interior_grid: THREE.MeshStandardMaterial
    rim_black: THREE.MeshStandardMaterial
    rim_chrome: THREE.MeshStandardMaterial
    tires: THREE.MeshStandardMaterial
    Discs: THREE.MeshStandardMaterial
    brakes: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model({ url = '/models/porsche-desktop.glb', ...props }: JSX.IntrinsicElements['group'] & { url?: string }) {
  const { nodes, materials } = useGLTF(url) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="SceneRoot" position={[2.291, 0.16, 0]}>
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="4dfb324c49be41728557ed99fef9dd07fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group name="RootNode">
                <group name="reisin_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="reisin_all_reisin_0" geometry={nodes.reisin_all_reisin_0?.geometry} material={materials.reisin} position={[-202.354, 0, 61.688]} scale={84.057} />
                </group>
                <group name="plastic_exterior" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="plastic_exterior_bl_pl_M_ext_0" geometry={nodes.plastic_exterior_bl_pl_M_ext_0?.geometry} material={materials.bl_pl_M_ext} position={[-229.392, 0, 52.007]} scale={226.349} />
                </group>
                <group name="windows_main" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="windows_main_windows_0" geometry={nodes.windows_main_windows_0?.geometry} material={materials.windows} position={[-261.178, 0, 89.239]} scale={130.252} />
                  <mesh name="windows_main_windows_edge_0" geometry={nodes.windows_main_windows_edge_0?.geometry} material={materials.windows_edge} position={[-261.178, 0, 89.239]} scale={130.252} />
                </group>
                <group name="black_metal_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="black_metal_all_black_metal_0" geometry={nodes.black_metal_all_black_metal_0?.geometry} material={materials.black_metal} position={[-227.254, 0, 28.681]} scale={134.354} />
                </group>
                <group name="mirror_middle" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="mirror_middle_Mirror_0" geometry={nodes.mirror_middle_Mirror_0?.geometry} material={materials.Mirror} position={[-202.452, 0, 98.035]} scale={10.555} />
                </group>
                <group name="carbon_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="carbon_all_carbon_int_0" geometry={nodes.carbon_all_carbon_int_0?.geometry} material={materials.carbon_int} position={[-207.704, 0, 51.515]} scale={63.513} />
                </group>
                <group name="body_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="body_all_body_main_0" geometry={nodes.body_all_body_main_0?.geometry} material={materials.body_main} position={[-229.081, 0, 56.685]} scale={226.716} />
                </group>
                <group name="lights_pattern_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="lights_pattern_all_headlights_pattern_0" geometry={nodes.lights_pattern_all_headlights_pattern_0?.geometry} material={materials.headlights_pattern} position={[-227.547, 0, 44.794]} scale={213.156} />
                </group>
                <group name="window_black_transparent" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="window_black_transparent_windows_dots_0" geometry={nodes.window_black_transparent_windows_dots_0?.geometry} material={materials.windows_dots} position={[-262.947, 0, 90.272]} scale={123.806} />
                </group>
                <group name="body_circles" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="body_circles_body_main_0" geometry={nodes.body_circles_body_main_0?.geometry} material={materials.body_main} position={[-227.295, -8.978, 49.281]} scale={222.43} />
                  <mesh name="body_circles_invisible_all_0" geometry={nodes.body_circles_invisible_all_0?.geometry} material={materials.invisible_all} position={[-135.661, -84.145, 63.781]} scale={10.402} />
                </group>
                <group name="number_plate" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="number_plate_number_plate1_0" geometry={nodes.number_plate_number_plate1_0?.geometry} material={materials.number_plate1} position={[-450.775, -0.023, 39.179]} scale={25.874} />
                </group>
                <group name="monitors_seconds" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="monitors_seconds_monitor_0" geometry={nodes.monitors_seconds_monitor_0?.geometry} material={materials.monitor} position={[-190.466, 17.066, 80.117]} scale={38.82} />
                </group>
                <group name="reflectors_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="reflectors_all_reflectors_0" geometry={nodes.reflectors_all_reflectors_0?.geometry} material={materials.reflectors} position={[-426.826, 0, 51.038]} scale={86.302} />
                </group>
                <group name="red_light_back" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="red_light_back_red_light_main_0" geometry={nodes.red_light_back_red_light_main_0?.geometry} material={materials.red_light_main} position={[-426.441, 0, 61.844]} scale={73.058} />
                </group>
                <group name="service_black" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="service_black_invisible_all_0" geometry={nodes.service_black_invisible_all_0?.geometry} material={materials.invisible_all} position={[-228.559, 0, 52.497]} scale={218.535} />
                </group>
                <group name="glossy_plastic" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="glossy_plastic_bl_pl__GL_int_ext_0" geometry={nodes.glossy_plastic_bl_pl__GL_int_ext_0?.geometry} material={materials.bl_pl__GL_int_ext} position={[-242.57, 0, 57.254]} scale={203.703} />
                </group>
                <group name="chrome_int" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="chrome_int_chrom_int_0" geometry={nodes.chrome_int_chrom_int_0?.geometry} material={materials.chrom_int} position={[-124.917, 0, 46.944]} scale={110.55} />
                </group>
                <group name="headlights_flash" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="headlights_flash_lights_0" geometry={nodes.headlights_flash_lights_0?.geometry} material={materials.lights} position={[-60.293, 0, 56.895]} scale={78.011} />
                </group>
                <group name="pipes" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="pipes_pipes_chrom_0" geometry={nodes.pipes_pipes_chrom_0?.geometry} material={materials.pipes_chrom} position={[-447.69, 0, 15.528]} scale={53.675} />
                </group>
                <group name="steering_wheel_signs" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="steering_wheel_signs_pl_leather_int_0" geometry={nodes.steering_wheel_signs_pl_leather_int_0?.geometry} material={materials.pl_leather_int} position={[-206.358, 33.99, 61.407]} scale={3.155} />
                </group>
                <group name="plast_leather_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="plast_leather_all_pl_leather_int_0" geometry={nodes.plast_leather_all_pl_leather_int_0?.geometry} material={materials.pl_leather_int} position={[-273.779, 0, 63.327]} scale={112.433} />
                </group>
                <group name="dynamics_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="dynamics_all_dynamics_0" geometry={nodes.dynamics_all_dynamics_0?.geometry} material={materials.dynamics} position={[-261.586, 0, 75.226]} scale={61.855} />
                </group>
                <group name="trans_covers" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="trans_covers_lights_0" geometry={nodes.trans_covers_lights_0?.geometry} material={materials.lights} position={[-233.807, 0, 64.335]} scale={220.769} />
                </group>
                <group name="upholstery_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="upholstery_all_upholstery_0" geometry={nodes.upholstery_all_upholstery_0?.geometry} material={materials.upholstery} position={[-263.69, 0, 101.102]} scale={61.212} />
                </group>
                <group name="logo_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="logo_all_LOGO1_0" geometry={nodes.logo_all_LOGO1_0?.geometry} material={materials.LOGO1} position={[-185.836, -0.003, 55.022]} scale={167.587} />
                </group>
                <group name="belts_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="belts_all_belts_0" geometry={nodes.belts_all_belts_0?.geometry} material={materials.belts} position={[-300.445, 0, 46.778]} scale={62.157} />
                </group>
                <group name="headlights_plastics" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="headlights_plastics_hedlights_grid_0" geometry={nodes.headlights_plastics_hedlights_grid_0?.geometry} material={materials.hedlights_grid} position={[-49.615, 0, 48.123]} scale={72.55} />
                  <mesh name="headlights_plastics_headlights_plastic_ring_0" geometry={nodes.headlights_plastics_headlights_plastic_ring_0?.geometry} material={materials.headlights_plastic_ring} position={[-63.737, 0, 57.678]} scale={79.766} />
                </group>
                <group name="rugs_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="rugs_all_rug_interior_0" geometry={nodes.rugs_all_rug_interior_0?.geometry} material={materials.rug_interior} position={[-260.622, 0, 44.577]} scale={132.035} />
                </group>
                <group name="leather_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="leather_all_leather_int_0" geometry={nodes.leather_all_leather_int_0?.geometry} material={materials.leather_int} position={[-251.515, 0, 50.186]} scale={84.852} />
                  <mesh name="leather_all_leather_seam_0" geometry={nodes.leather_all_leather_seam_0?.geometry} material={materials.leather_seam} position={[-226.083, -0.001, 53.019]} scale={67.467} />
                  <mesh name="leather_all_leather_perforated_0" geometry={nodes.leather_all_leather_perforated_0?.geometry} material={materials.leather_perforated} position={[-238.738, 0, 40.846]} scale={55.354} />
                </group>
                <group name="plastic_all" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="plastic_all_bl_pl_M_int_0" geometry={nodes.plastic_all_bl_pl_M_int_0?.geometry} material={materials.bl_pl_M_int} position={[-294.912, 0, 53.944]} scale={159.796} />
                  <mesh name="plastic_all_bl_pl_M_int_0_1" geometry={nodes.plastic_all_bl_pl_M_int_0_1?.geometry} material={materials.bl_pl_M_int} position={[-246.05, 0, 48.884]} scale={104.044} />
                  <mesh name="plastic_all_interior_grid_0" geometry={nodes.plastic_all_interior_grid_0?.geometry} material={materials.interior_grid} position={[-187.558, 0, 59.837]} scale={57.43} />
                </group>
                <group name="door_1" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="mirror_door_1">
                    <mesh name="mirror_door_1_Mirror_0" geometry={nodes.mirror_door_1_Mirror_0?.geometry} material={materials.Mirror} position={[-200.414, -92.01, 78.298]} scale={8.411} />
                  </group>
                  <group name="reisin__door_1">
                    <mesh name="reisin__door_1_reisin_0" geometry={nodes.reisin__door_1_reisin_0?.geometry} material={materials.reisin} position={[-223.568, -85.171, 48.25]} scale={60.192} />
                  </group>
                  <group name="plastic_exterior_door_1">
                    <mesh name="plastic_exterior_door_1_bl_pl_M_ext_0" geometry={nodes.plastic_exterior_door_1_bl_pl_M_ext_0?.geometry} material={materials.bl_pl_M_ext} position={[-226.182, -84.71, 73.722]} scale={53.353} />
                  </group>
                  <group name="carbon__door_1">
                    <mesh name="carbon__door_1_carbon_int_0" geometry={nodes.carbon__door_1_carbon_int_0?.geometry} material={materials.carbon_int} position={[-245.447, -67.867, 65.863]} scale={25.325} />
                  </group>
                  <group name="dynamics_door_1">
                    <mesh name="dynamics_door_1_dynamics_0" geometry={nodes.dynamics_door_1_dynamics_0?.geometry} material={materials.dynamics} position={[-197.882, -69.039, 41.522]} scale={22.653} />
                  </group>
                  <group name="screw_door_1">
                    <mesh name="screw_door_1_black_metal_0" geometry={nodes.screw_door_1_black_metal_0?.geometry} material={materials.black_metal} position={[-274.458, -75.255, 45.587]} scale={4.933} />
                  </group>
                  <group name="logo_door_1">
                    <mesh name="logo_door_1_LOGO1_0" geometry={nodes.logo_door_1_LOGO1_0?.geometry} material={materials.LOGO1} position={[-208.881, -68.621, 55.56]} scale={13.119} />
                  </group>
                  <group name="reflector_door_1">
                    <mesh name="reflector_door_1_reflectors_0" geometry={nodes.reflector_door_1_reflectors_0?.geometry} material={materials.reflectors} position={[-239.582, -68.742, 24.55]} scale={4.087} />
                  </group>
                  <group name="leather_door_1">
                    <mesh name="leather_door_1_leather_int_0" geometry={nodes.leather_door_1_leather_int_0?.geometry} material={materials.leather_int} position={[-221.389, -68.206, 54.94]} scale={52.33} />
                    <mesh name="leather_door_1_leather_seam_0" geometry={nodes.leather_door_1_leather_seam_0?.geometry} material={materials.leather_seam} position={[-218.375, -66.296, 48.527]} scale={48.227} />
                  </group>
                  <group name="body__door_1">
                    <mesh name="body__door_1_body_main_0" geometry={nodes.body__door_1_body_main_0?.geometry} material={materials.body_main} position={[-220.157, -85.633, 47.914]} scale={64.966} />
                  </group>
                  <group name="window_door_1">
                    <mesh name="window_door_1_windows_0" geometry={nodes.window_door_1_windows_0?.geometry} material={materials.windows} position={[-235.409, -66.168, 87.52]} scale={50.021} />
                    <mesh name="window_door_1_windows_edge_0" geometry={nodes.window_door_1_windows_edge_0?.geometry} material={materials.windows_edge} position={[-235.409, -66.16, 87.52]} scale={50.021} />
                  </group>
                  <group name="plastic_door_1">
                    <mesh name="plastic_door_1_bl_pl_M_int_0" geometry={nodes.plastic_door_1_bl_pl_M_int_0?.geometry} material={materials.bl_pl_M_int} position={[-229.003, -71.116, 52.61]} scale={45.906} />
                  </group>
                  <group name="mirror_cover_door_1">
                    <mesh name="mirror_cover_door_1_monitor_0" geometry={nodes.mirror_cover_door_1_monitor_0?.geometry} material={materials.monitor} position={[-200.48, -91.987, 78.304]} scale={8.593} />
                  </group>
                  <group name="chrome_door_1">
                    <mesh name="chrome_door_1_chrom_int_0" geometry={nodes.chrome_door_1_chrom_int_0?.geometry} material={materials.chrom_int} position={[-224.719, -68.573, 52.655]} scale={47.417} />
                  </group>
                  <group name="leathplast_door_1">
                    <mesh name="leathplast_door_1_pl_leather_int_0" geometry={nodes.leathplast_door_1_pl_leather_int_0?.geometry} material={materials.pl_leather_int} position={[-217.386, -68.021, 39.491]} scale={48.225} />
                  </group>
                </group>
                <group name="door_2" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="mirror_door_2">
                    <mesh name="mirror_door_2_Mirror_0" geometry={nodes.mirror_door_2_Mirror_0?.geometry} material={materials.Mirror} position={[-200.414, 92.01, 78.298]} scale={8.411} />
                  </group>
                  <group name="body_door_2">
                    <mesh name="body_door_2_body_main_0" geometry={nodes.body_door_2_body_main_0?.geometry} material={materials.body_main} position={[-220.157, 85.633, 47.914]} scale={64.966} />
                  </group>
                  <group name="plastic_door_2">
                    <mesh name="plastic_door_2_bl_pl_M_int_0" geometry={nodes.plastic_door_2_bl_pl_M_int_0?.geometry} material={materials.bl_pl_M_int} position={[-229.003, 71.116, 52.61]} scale={45.906} />
                  </group>
                  <group name="leath_plast_door_2">
                    <mesh name="leath_plast_door_2_pl_leather_int_0" geometry={nodes.leath_plast_door_2_pl_leather_int_0?.geometry} material={materials.pl_leather_int} position={[-217.386, 68.021, 39.491]} scale={48.225} />
                  </group>
                  <group name="chrome__door_2">
                    <mesh name="chrome__door_2_chrom_int_0" geometry={nodes.chrome__door_2_chrom_int_0?.geometry} material={materials.chrom_int} position={[-224.707, 68.573, 52.59]} scale={47.428} />
                  </group>
                  <group name="dynamic_door_2">
                    <mesh name="dynamic_door_2_dynamics_0" geometry={nodes.dynamic_door_2_dynamics_0?.geometry} material={materials.dynamics} position={[-197.882, 69.039, 41.522]} scale={22.653} />
                  </group>
                  <group name="body_all_Ext_3">
                    <mesh name="body_all_Ext_3_body_main_0" geometry={nodes.body_all_Ext_3_body_main_0?.geometry} material={materials.body_main} position={[-267.11, 85.05, 56.346]} scale={11.353} />
                  </group>
                  <group name="reflectors__door_2">
                    <mesh name="reflectors__door_2_reflectors_0" geometry={nodes.reflectors__door_2_reflectors_0?.geometry} material={materials.reflectors} position={[-239.582, 68.742, 24.55]} scale={4.087} />
                  </group>
                  <group name="carbon__door_2">
                    <mesh name="carbon__door_2_carbon_int_0" geometry={nodes.carbon__door_2_carbon_int_0?.geometry} material={materials.carbon_int} position={[-245.447, 67.867, 65.863]} scale={25.325} />
                  </group>
                  <group name="logo_door_2">
                    <mesh name="logo_door_2_LOGO1_0" geometry={nodes.logo_door_2_LOGO1_0?.geometry} material={materials.LOGO1} position={[-208.881, 68.621, 55.562]} scale={13.121} />
                  </group>
                  <group name="screw_door_2">
                    <mesh name="screw_door_2_black_metal_0" geometry={nodes.screw_door_2_black_metal_0?.geometry} material={materials.black_metal} position={[-274.458, 75.255, 45.587]} scale={4.933} />
                  </group>
                  <group name="leather_door_2">
                    <mesh name="leather_door_2_leather_int_0" geometry={nodes.leather_door_2_leather_int_0?.geometry} material={materials.leather_int} position={[-221.389, 68.206, 54.94]} scale={52.33} />
                    <mesh name="leather_door_2_leather_seam_0" geometry={nodes.leather_door_2_leather_seam_0?.geometry} material={materials.leather_seam} position={[-218.375, 66.296, 48.527]} scale={48.227} />
                  </group>
                  <group name="plastic_exterior__door_2">
                    <mesh name="plastic_exterior__door_2_bl_pl_M_ext_0" geometry={nodes.plastic_exterior__door_2_bl_pl_M_ext_0?.geometry} material={materials.bl_pl_M_ext} position={[-226.172, 84.71, 73.722]} scale={53.363} />
                  </group>
                  <group name="reisin__door_2">
                    <mesh name="reisin__door_2_reisin_0" geometry={nodes.reisin__door_2_reisin_0?.geometry} material={materials.reisin} position={[-223.569, 85.171, 48.25]} scale={60.192} />
                  </group>
                  <group name="window_door_2">
                    <mesh name="window_door_2_windows_0" geometry={nodes.window_door_2_windows_0?.geometry} material={materials.windows} position={[-235.409, 66.168, 87.52]} scale={50.021} />
                    <mesh name="window_door_2_windows_edge_0" geometry={nodes.window_door_2_windows_edge_0?.geometry} material={materials.windows_edge} position={[-235.409, 66.16, 87.52]} scale={50.021} />
                  </group>
                  <group name="mirror_cover_door_2">
                    <mesh name="mirror_cover_door_2_monitor_0" geometry={nodes.mirror_cover_door_2_monitor_0?.geometry} material={materials.monitor} position={[-200.48, 91.987, 78.304]} scale={8.593} />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name="wheel_FL" position={[-1.038, 0.189, -0.778]}>
            <mesh name="wheel_FL_wheel_rim_rim_black_0" geometry={nodes.wheel_FL_wheel_rim_rim_black_0?.geometry} material={materials.rim_black} position={[0, 0, -0.009]} scale={0.266} />
            <mesh name="wheel_FL_wheel_rim_rim_chrome_0" geometry={nodes.wheel_FL_wheel_rim_rim_chrome_0?.geometry} material={materials.rim_chrome} position={[0, 0, -0.115]} scale={0.272} />
            <mesh name="wheel_FL_AO_tire_main_tires_0" geometry={nodes.wheel_FL_AO_tire_main_tires_0?.geometry} material={materials.tires} scale={0.336} />
            <mesh name="wheel_FL_discs_Discs_0" geometry={nodes.wheel_FL_discs_Discs_0?.geometry} material={materials.Discs} position={[0, 0, -0.034]} scale={0.21} />
          </group>
          <group name="wheel_FR" position={[-1.038, 0.189, 0.778]}>
            <mesh name="wheel_FR_wheel_rim_rim_black_0" geometry={nodes.wheel_FR_wheel_rim_rim_black_0?.geometry} material={materials.rim_black} position={[0, 0, 0.009]} scale={0.266} />
            <mesh name="wheel_FR_wheel_rim_rim_chrome_0" geometry={nodes.wheel_FR_wheel_rim_rim_chrome_0?.geometry} material={materials.rim_chrome} position={[0, 0, 0.115]} scale={0.272} />
            <mesh name="wheel_FR_AO_tire_main_tires_0" geometry={nodes.wheel_FR_AO_tire_main_tires_0?.geometry} material={materials.tires} scale={0.336} />
            <mesh name="wheel_FR_discs_Discs_0" geometry={nodes.wheel_FR_discs_Discs_0?.geometry} material={materials.Discs} position={[0, 0, 0.034]} scale={0.21} />
          </group>
          <group name="wheel_RL" position={[-3.489, 0.194, -0.785]}>
            <mesh name="wheel_RL_wheel_rim_rim_black_0" geometry={nodes.wheel_RL_wheel_rim_rim_black_0?.geometry} material={materials.rim_black} position={[0, -0.001, -0.003]} scale={0.28} />
            <mesh name="wheel_RL_wheel_rim_rim_chrome_0" geometry={nodes.wheel_RL_wheel_rim_rim_chrome_0?.geometry} material={materials.rim_chrome} position={[0, -0.001, -0.146]} scale={0.286} />
            <mesh name="wheel_RL_AO_tire_main_tires_0" geometry={nodes.wheel_RL_AO_tire_main_tires_0?.geometry} material={materials.tires} scale={0.354} />
            <mesh name="wheel_RL_discs_Discs_0" geometry={nodes.wheel_RL_discs_Discs_0?.geometry} material={materials.Discs} position={[0, -0.001, -0.023]} scale={0.196} />
          </group>
          <group name="wheel_RR" position={[-3.489, 0.194, 0.785]}>
            <mesh name="wheel_RR_wheel_rim_rim_black_0" geometry={nodes.wheel_RR_wheel_rim_rim_black_0?.geometry} material={materials.rim_black} position={[0, -0.001, 0.003]} scale={0.28} />
            <mesh name="wheel_RR_wheel_rim_rim_chrome_0" geometry={nodes.wheel_RR_wheel_rim_rim_chrome_0?.geometry} material={materials.rim_chrome} position={[0, -0.001, 0.146]} scale={0.286} />
            <mesh name="wheel_RR_AO_tire_main_tires_0" geometry={nodes.wheel_RR_AO_tire_main_tires_0?.geometry} material={materials.tires} scale={0.354} />
            <mesh name="wheel_RR_discs_Discs_0" geometry={nodes.wheel_RR_discs_Discs_0?.geometry} material={materials.Discs} position={[0, -0.001, 0.023]} scale={0.196} />
          </group>
          <mesh name="brake_FL" geometry={nodes.brake_FL?.geometry} material={materials.brakes} position={[-1.197, 0.214, -0.785]} scale={0.186} />
          <mesh name="brake_FR" geometry={nodes.brake_FR?.geometry} material={materials.brakes} position={[-1.197, 0.214, 0.785]} scale={0.186} />
          <mesh name="brake_RL" geometry={nodes.brake_RL?.geometry} material={materials.brakes} position={[-3.332, 0.139, -0.779]} scale={0.139} />
          <mesh name="brake_RR" geometry={nodes.brake_RR?.geometry} material={materials.brakes} position={[-3.332, 0.139, 0.779]} scale={0.139} />
          <mesh name="hardware_FL" geometry={nodes.hardware_FL?.geometry} material={materials.rim_chrome} position={[-1.459, 0.202, -0.319]} scale={0.211} />
          <mesh name="hardware_FR" geometry={nodes.hardware_FR?.geometry} material={materials.rim_chrome} position={[-1.457, 0.202, 0.485]} scale={0.136} />
          <mesh name="hardware_RL" geometry={nodes.hardware_RL?.geometry} material={materials.rim_chrome} position={[-3.608, 0.48, -0.369]} scale={0.916} />
          <mesh name="hardware_RR" geometry={nodes.hardware_RR?.geometry} material={materials.rim_chrome} position={[-3.608, 0.48, 0.37]} scale={0.916} />
        </group>
      </group>
    </group>
  )
}

